# Generated by Django 3.2.7 on 2023-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatienceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('disease_type', models.CharField(max_length=100)),
                ('drugs', models.CharField(max_length=100)),
            ],
        ),
    ]
