# Generated by Django 3.2.7 on 2023-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
